# Generated by Django 5.2.7 on 2025-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('site_generator', '0004_templateranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects_created',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='site_generator.templategenerator'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='site_generator.templategenerator'),
        ),
    ]
