# Generated by Django 5.2.7 on 2025-10-11 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('site_generator', '0004_templateranked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('created_templates', models.ManyToManyField(blank=True, null=True, related_name='authors', to='site_generator.templategenerator')),
                ('downloaded_templates', models.ManyToManyField(blank=True, null=True, related_name='customers', to='site_generator.templategenerator')),
                ('favorite_templates', models.ManyToManyField(blank=True, null=True, related_name='users', to='site_generator.templategenerator')),
            ],
        ),
    ]
