# Generated by Django 5.2.7 on 2025-10-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
