# Generated by Django 5.2.7 on 2025-10-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_username'),
        ('site_generator', '0005_alter_templategenerator_css_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='created_templates',
            field=models.ManyToManyField(blank=True, related_name='authors', to='site_generator.templategenerator'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='downloaded_templates',
            field=models.ManyToManyField(blank=True, related_name='customers', to='site_generator.templategenerator'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='favorite_templates',
            field=models.ManyToManyField(blank=True, related_name='users', to='site_generator.templategenerator'),
        ),
    ]
