# Generated by Django 5.2.7 on 2025-10-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80)),
                ('template_names', models.JSONField(default=list)),
                ('css_files', models.JSONField(default=list)),
                ('js_files', models.JSONField(default=list)),
            ],
        ),
    ]
