# Generated by Django 5.2.7 on 2025-10-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templategenerator',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='templategenerator',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='projects/previews'),
        ),
        migrations.AddField(
            model_name='templategenerator',
            name='slug',
            field=models.SlugField(default='generic', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
