# Generated by Django 5.2.7 on 2025-10-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_generator', '0002_templategenerator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templategenerator',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='projects/preview'),
        ),
    ]
