# Generated by Django 5.2.7 on 2025-10-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_generator', '0003_alter_templategenerator_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRanked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.IntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='site_generator.templategenerator')),
            ],
        ),
    ]
