# Generated by Django 5.2.7 on 2025-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_generator', '0004_templateranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templategenerator',
            name='css_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='templategenerator',
            name='js_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='templategenerator',
            name='template_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
