# Generated by Django 5.2.7 on 2025-10-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_generator', '0005_alter_templategenerator_css_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templategenerator',
            name='img_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
